name: Build gap for all platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            install: sudo apt install libglx-dev libx11-dev libxext-dev libxrandr-dev
            build: ./build.sh release
          - os: windows-latest
            install: echo "Nothing to install"
            build: ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && ./build.bat release' }}
          - os: macos-latest
            install: chmod +x ./build-mac.sh
            build: ./build-mac.sh release

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: ${{ matrix.install }}
    - name: Build
      run: ${{ matrix.build }}
