name: Build gap for all platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            shell: bash
            install: sudo apt install libgl-dev libglx-dev libx11-dev libxext-dev libxrandr-dev
            build: ./build.sh release
            
          - os: windows-latest
            shell: cmd
            install: echo "Skipping install for Windows"
            build: |
              call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              build.bat release
              
          - os: macos-latest
            shell: bash
            install: pwd && ls -al
            build: bash ./build-mac.sh release

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      shell: ${{ matrix.shell }}
      run: ${{ matrix.install }}
      
    - name: Build
      shell: ${{ matrix.shell }}
      run: ${{ matrix.build }}
